# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            UGA Web Accessibility Group
tagline:          ''
description:      ''
url:              http://web-accessibility-group.github.io/
baseurl:          /

author:
  name:           ''
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/web-accessibility-group/web-accessibility-group.github.io
